= The one with the flow

Since the `BroadcastChannel` is obsolete and its docs suggest to use the `SharedFlow` instead,
it's time to look into https://kotlinlang.org/docs/flow.html#flows[Kotlin Asynchronous Flow].

== Playing with flows

Flow is similar to streams from usage perspective:

[source,kotlin]
.frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt
----
include::git@frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt[revision=6edbb5f8f107bdced3450933bd384e52898da94c]
----

For our project, I'm interested in the `SharedFlow`. It might not be currently documented in user docs, but
https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-shared-flow/[API docs]
fill that gap pretty well.

[quote,SharedFlow]
----
SharedFlow is useful for broadcasting events that happen inside an application to subscribers that can come and go.
----

Sounds like exactly what I need.

`SharedFlow` docs even have an example of an `EventBus` that I could play with:

[source,kotlin]
.frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt
----
include::git@frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt[revision=4980cba3708d843b603c60392e51a748eb8cc060,lines=58..70,indent=0]
----

Feeling I'm getting closer to something I could use I defined some example events:

[source,kotlin]
.frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt
----
include::git@frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt[revision=4980cba3708d843b603c60392e51a748eb8cc060,lines=72..74,indent=0]
----

and wrote an example of how to use the event bus:

[source,kotlin]
.frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt
----
include::git@frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt[revision=4980cba3708d843b603c60392e51a748eb8cc060,lines=29..57,indent=0]
----

In real life, instead of using `Flow.take()` to consume a fixed number of events:

[source,kotlin]
----
include::git@frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt[revision=ea6ebc2fd41494437185b23ef1387f32ac663d46,lines=34,indent=0]
----

I'd use something like `Flow.takeWhile()` instead:

[source,kotlin]
----
include::git@frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt[revision=ea6ebc2fd41494437185b23ef1387f32ac663d46,lines=65,indent=0]
----

That would require publishing a special event to terminate the flow:

[source,kotlin]
----
include::git@frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt[revision=ea6ebc2fd41494437185b23ef1387f32ac663d46,lines=108,indent=0]
----

[source,kotlin]
----
include::git@frame/src/test/kotlin/pl/zalas/frame/LearnFlowsTest.kt[revision=ea6ebc2fd41494437185b23ef1387f32ac663d46,lines=79,indent=0]
----

Promising!
